### ISSUE TITLE
Move to Archive

### ISSUE THREAD

**Issue by aspdye** [owncloud-archive/shorty#131]
I think, because this app is unmaintained, we should move this repository to ownCloud archive :wink: 

cc @DeepDiver1975

**Comment by arkascha** [comment]
Fine from my side too, I actually suggested to delete it months ago.

**Comment by DeepDiver1975** [comment]
@karlitschek shall I execute as requested?

**Comment by karlitschek** [comment]
not sure. there is still the small option that someone picks this up in the future. so unmaintains is not the right metric to remove something. let's leave it here for now

**Comment by aspdye** [comment]
But can we stop the Transifex robot importing for this repo?
